version: "3.7"

services:
    redis-master:
        image: 'bitnami/redis:5.0'
        environment:
                - ALLOW_EMPTY_PASSWORD=yes

    postgres:
        image: 'postgres:12.2-alpine'
        environment:
            - POSTGRES_USER=pybossa
            - POSTGRES_PASSWORD=supersecretpassword

    # initializes the database
    db-init:
       image: 'helpful-pybossa:latest'
       depends_on:
           - postgres
       environment:
           - POSTGRES_URL=postgresql://pybossa:supersecretpassword@postgres/pybossa
       links:
           - postgres:db
       command: sh -c "sleep 5 && python cli.py db_create"

    pybossa-bgworker:
        image: 'helpful-pybossa:latest'
        depends_on:
            - db-init
        environment:
            - POSTGRES_URL=postgresql://pybossa:supersecretpassword@postgres/pybossa
        links:
            - redis-master
            - postgres
        entrypoint: /entrypoint.sh
        command:  sh -c "python app_context_rqworker.py scheduled_jobs super high medium low email maintenance"

    pybossa-scheduler:
        image: 'helpful-pybossa:latest'
        depends_on: 
            - db-init
        environment:
            - POSTGRES_URL=postgresql://pybossa:supersecretpassword@postgres/pybossa
        links:
            - redis-master
            - postgres
        entrypoint: /entrypoint.sh
        command:  sh -c "rqscheduler --host redis-master"
    
    # web server
    pybossa_app:
        image: 'helpful-pybossa:latest'
        container_name: pybossa-app
        depends_on:
            - pybossa-bgworker
            - db-init
        environment:
            - POSTGRES_URL=postgresql://pybossa:supersecretpassword@postgres/pybossa
            - REDIS_HOST=redis-master
            - HTTPS=on
            - wsgi.url_scheme='https'
            - HEALTHSITES_API_KEY
        links:
            - redis-master
            - postgres
        ports:
            - "8080:8080"
